# Default values for auth-otus-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

fullnameOverride: "auth-otus"

image: jawello/auth-otus:0.0.1

service:
  type: NodePort
  port: 9000

appservice:
  url: 'http://users-otus:8000/users'

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: arch.homework
      paths:
        - /auth
        - /registration
        - /session
        - /signin

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: otus
  postgresqlDatabase: postgres
  service:
    port: "5432"

redis:
  enabled: true
  usePassword: false
  redisPort: "6379"
  cluster:
    enabled: false