apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-otus-chart.fullname" . }}
  labels:
    {{- include "auth-otus-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "auth-otus-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "auth-otus-chart.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/app-config.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: check-db-ready
          image: postgres:11-alpine
          command: ['sh', '-c',
                    'until pg_isready -h {{ (include "postgresql.fullname" .) }} -p 5432;
                      do echo waiting for database; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          volumeMounts:
            - name: auth-otus-config-volume
              mountPath: /app/config
      volumes:
        - name: auth-otus-config-volume
          configMap:
            name: auth-otus-config